version: '2'

services:  
  sql:
    image: mcmoe/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 4open!4open
      MSSQL_PID: Developer
      MSSQL_DB: Subscription
      MSSQL_USER: testUser
      MSSQL_PASSWORD: password
    ports:
      - 1433:1433           
    
  rabbit:    
    image: rafakato/rabbitmq-delayed-message-exchange:3.6.1-management
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_DEFAULT_VHOST: test-gis-by        
    ports:
      - 5672:5672
      - 15672:15672
    